kind: Service
apiVersion: v1
metadata:
  name: prompts
  labels:
    app: prompts
spec:
  type: ClusterIP
  selector:
    app: prompts
  ports:
    - name: tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: prompts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prompts
  template:
    metadata:
      labels:
        app: prompts
        version: v1
    spec:
      containers:
      - name: prompts
        image: prompts
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
